export const pricingHeader = {
  title: "Simple, transparent pricing",
  description: "Choose the plan that best fits your business. No hidden fees, ever.",
}

export const pricingTiers = [
  {
    name: "Free Trial",
    id: "tier-free-trial",
    priceMonthly: "Free",
    price6Month: "Free",
    priceYearly: "Free",
    description: "Perfect for small gyms and studios just getting started.",
    features: [
      "Up to 100 members",
      "Basic member management",
      "Automated billing (1 currency)",
      "Standard attendance tracking",
      "Email support",
    ],
    mostPopular: false,
  },
  {
    name: "Starter",
    id: "tier-starter",
    priceMonthly: "8,999 ETB",
    price6Month: "8,099 ETB",
    priceYearly: "7,199 ETB",
    description: "Perfect for small gyms and studios just getting started.",
    features: [
      "Up to 100 members",
      "Basic member management",
      "Automated billing (1 currency)",
      "Standard attendance tracking",
      "Email support",
    ],
    mostPopular: false,
  },
  {
    name: "Professional",
    id: "tier-professional",
    priceMonthly: "9,999 ETB",
    price6Month: "8,999 ETB",
    priceYearly: "7,999 ETB",
    description: "Advanced features for growing fitness centers.",
    features: [
      "Up to 1,000 members",
      "Advanced member analytics",
      "Automated billing (Multi-currency)",
      "QR & RFID attendance",
      "Priority email & chat support",
      "Marketing automation",
    ],
    mostPopular: true,
  },
  {
    name: "Enterprise",
    id: "tier-enterprise",
    priceMonthly: "13,999 ETB",
    price6Month: "12,599 ETB",
    priceYearly: "11,199 ETB",
    description: "Full-scale solution for multi-location health clubs.",
    features: [
      "Unlimited members",
      "Multi-location management",
      "Full API access",
      "Biometric attendance",
      "Dedicated account manager",
      "Custom reporting",
      "White-label options",
    ],
    mostPopular: false,
  },
]
